#!/bin/bash

CURRENT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
pathToCode=/afs/cern.ch/user/f/fleble/utilities/utilities
arguments=$@

python ${pathToCode}/printPythonPackages/printPythonPackages.py ${arguments}
