#!/bin/bash

###################################  README  ###################################
HELP='
diffdir version 1.0

Description:
  Calculate difference between 2 directories

Synopsis:
  diffdir file1 file2 [-n]

Arguments:
  -n        Do not print files names in directories, but number of files
            (excluding folders)
'
################################################################################


bold=$(tput bold)
normal=$(tput sgr0)

## Creating/Emptying files to store directory structure

dir1Struct=/tmp/dir1Struct.txt
dir2Struct=/tmp/dir2Struct.txt
> ${dir1Struct}
> ${dir2Struct}


## Useful functions

makeTab() {
  tab=''
  for ((itab=0; itab<$1; itab++)); do tab=${tab}'    '; done
  echo "${tab}"
}

explore () {

  outFile=$3

  # If not -n flag
  if [ "${NFLAG}" == "0" ]; then
      for f in `ls $1`; do
          ntabs=$2
          tab=`makeTab $ntabs`
      
          # If not -n flag
          if [ -d $1/${f} ]; then
              echo -e "${tab}${f}/" >> ${outFile}
              explore $1/$f $(($ntabs+1)) ${outFile}
          elif [ -f $1/${f} ]; then
              echo "${tab}${f}" >> ${outFile}
          else
              echo "WARNING!!!"
          fi
      done

  # If -n flag
  else
      for f in `ls $1`; do
          ntabs=$2
          tab=`makeTab $ntabs`

          if [ -d $1/${f} ]; then
              n=`ls $1/${f} | grep -Ev "^d" | wc -l`
              echo -e "${tab}${f}/    \t(${n} files)" >> ${outFile}
              explore $1/$f $(($ntabs+1)) ${outFile}
          fi
      done
  fi

}


##############
###  Main  ###
##############

## Check number of arguments

ndirs=0
dirs_=()
for arg in "$@"; do
  if [ ! "${arg:0:1}" == "-" ]; then
    dirs_[${ndirs}]="$arg"
    ndirs=$((${ndirs}+1))
  fi
done

if [ ! ${ndirs} -eq 2 ]; then
  echo "ERROR: 2 directories are needed as arguments"
  echo "       See usage: diffdir -h"
  exit 1
fi


## Check if arguments are existing directories

for d in ${dirs_[@]}; do
  if [ ! -e $d ]; then
    echo "ERROR: ${d} does not exist"
    exit 1
  else
    if [ ! -d $d ]; then
      echo "ERROR: ${d} is not a directory"
      exit 1
    fi
  fi
done


## Check flags

NFLAG="0"

for arg in "$@"; do
  if [ "${arg:0:1}" == "-" ]; then
    if [ "${arg}" == "-n" ]; then
      NFLAG="1"
    elif [ "${arg}" == "-h" ]; then
      echo -e "${HELP}"
      exit 0
    fi
  fi
done


echo "${bold}Directory structure will be written to:${normal}"
echo "  ${dir1Struct}"
echo "  ${dir2Struct}"
echo ""

explore $1 0 ${dir1Struct}
explore $2 0 ${dir2Struct}

#f1=`cat ${dir1Struct}`
#for x in ${f1}; do echo ${x}; done

echo "${bold}Difference between directories:${normal}"
diff -y ${dir1Struct} ${dir2Struct} | sed 's/[><]//'
